name: Check SSH Private Key

on:
  workflow_dispatch:

jobs:
  check-ssh:
    runs-on: ubuntu-latest

    steps:
      - name: Print SSH private key fingerprint
        run: |
          echo "$SSH_PRIVATE_KEY" > key.pem
          chmod 600 key.pem
          ssh-keygen -y -f key.pem | ssh-keygen -lf -
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
